services:
  - type: web
    name: driving-education-site
    env: node
    buildCommand: chmod +x ./deploy.sh && ./deploy.sh
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    plan: free